# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 16:01
from __future__ import unicode_literals

import contactoApp.modelsC
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('contactoApp', '0001_initial'), ('contactoApp', '0002_contactorecursoshumanos'), ('contactoApp', '0003_contactorecursoshumanos_fecha'), ('contactoApp', '0004_auto_20160713_2311'), ('contactoApp', '0005_contactoingenia_mensaje_home'), ('contactoApp', '0006_auto_20160721_1615'), ('contactoApp', '0007_auto_20160721_1618'), ('contactoApp', '0008_auto_20160721_1620')]

    initial = True

    dependencies = [
        ('vacantesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoAplicante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=14)),
                ('cv', models.FileField(blank=True, upload_to=contactoApp.modelsC.path_and_rename_CV)),
                ('aplica_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacantesApp.Vacante')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoIngenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compania', models.CharField(default='Ingenia', max_length=30)),
                ('direccion', models.CharField(default=' Anatole France 311 - Polanco, Mexico D.F. ', max_length=140)),
                ('telefono', models.CharField(default='+51 (55) 50 2209 0000', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateField(auto_now=True)),
                ('mensaje_home', models.TextField(default='Hola')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoInteresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactoRecursosHumanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('puesto', models.CharField(max_length=60)),
                ('bio', models.TextField()),
                ('foto', models.ImageField(upload_to=contactoApp.modelsC.path_and_rename_foto)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 22, 16, 1, 6, 251329))),
            ],
        ),
    ]
