# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactoApp', '0001_squashed_0008_auto_20160721_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoingenia',
            name='mensaje_home',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactorecursoshumanos',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
