# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingeniaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingeniaimagen',
            name='seccion',
            field=models.CharField(choices=[('imagen_intro', 'Imagen Intro'), ('imagen_a1', 'Imagen Adicional 1'), ('imagen_a2', 'Imagen Adicional 2')], max_length=50),
        ),
    ]
